### ISSUE TITLE
Fixed point ore deposit

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#100]
RA3 ore mines, Generals supply stack, KKND style... etc.

Dock and fill the storage trait I guess.

**Comment by GraionDilach** [comment]
Start with reading https://github.com/Holloweye/OpenRA/blob/bleed/OpenRA.Mods.WWI/Traits/Trader.cs IMO, it works visually like Gen supply docks (except with scaled income based on distance).

**Comment by forcecore** [comment]
Erm... I forgot why I needed this lol
