### ISSUE TITLE
My Contrail.is out-dated for some reason

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#107]
WHAT?!
DIDN"T I MERGE STABLE-20170421 ??
I mean, that contrail.cs is in MARCH fix

**Comment by GraionDilach** [comment]
March indeed, but the first playtest was released before it. That fix is only in bleed.

**Comment by forcecore** [comment]
Ugh, terrible. I'd have to cherry pick that one

**Comment by forcecore** [comment]
Cherry picked the fixing commit
