### ISSUE TITLE
Super Tank husks have cyainsh flames.

### ISSUE THREAD

**Issue by GraionDilach** [forcecore/yupgi_alert0#125]

**Comment by forcecore** [comment]
Burns.cs problem, more complicated than I thought xD

**Comment by forcecore** [comment]
Looking at Burn.cs, this seems to be reverse of self heal with animation overlay. Maybe it is better to remove burns.cs then split into two traits: selfheal with -damage and anim overlay.

**Comment by forcecore** [comment]
https://github.com/OpenRA/OpenRA/issues/7115

https://github.com/OpenRA/OpenRA/wiki/Traits#withdamageoverlay
is the closest thing to WithConditionedOverlay

+ SelfHeal with a little bit of polishing can replace Burn.cs

**Comment by GraionDilach** [comment]
You don't need polishing. SelfHeal + WithIdleOverlay is your friend.

**Comment by forcecore** [comment]
WithIdleOverlay takes only Sequence parameter so unless you combine flame animation into the unit that will not work?

**Comment by GraionDilach** [comment]
You can take WithIdleOverlayAS then (it breaks the lint tests though).

**Comment by forcecore** [comment]
WithIdleOverlay gets affected by black-ish DisabledOverlay not not suitable. Monkey patched Burns.cs instead.
