### ISSUE TITLE
SHP builder RA1 cameo support

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#152]
not too sure about license but maybe I can fork and patch then PR?

**Comment by GraionDilach** [comment]
It has an OS license - notsure which myself either suddenly - but sure you can fork and patch. Although the repo is at http://svn.ppmsite.com/listing.php?repname=OS+SHP+Builder so you can't send a PR.

**Comment by forcecore** [comment]
Deciding between GIMP plugin vs SHP builder hmmm

SHP builder: supports making SHP directly. Can use already existing logic

GIMP: cameo support only requires placing letters. Color conversion and stuff an be done easily with GIMP index coloring or XCC Mixer

I'm leaning towards GIMP, it works (won't test but will work) on Linux...

**Comment by GraionDilach** [comment]
SHP Builder works through Wine already though. Doesn't matter much I guess.

**Comment by forcecore** [comment]
Gimp plugin: ef2c388e3075e6eaab1d7c26e80ebc6df321a158
