### ISSUE TITLE
Doggies

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#191]
Looks like a good one to "spam" the PR queue

https://github.com/OpenRA/OpenRA/issues/7506

**Comment by forcecore** [comment]
https://www.youtube.com/watch?v=dPebWxuiuc4
https://www.youtube.com/watch?v=sIuHmrL1PRY

**Comment by ABrandau** [comment]
btw, afaik the current attack leap trait ignores weapon damage and attack speed?

**Comment by MustaphaTR** [comment]
Not sure about speed, but it indeed does ignore damage, i noticed when trying to add Terror Drones to my D2K mod.

**Comment by GraionDilach** [comment]
Yes, it ignores reload delays as well, doesn't apply damagetypes and similar. The old dog PR however axes AttackLeap entirely IIRC in favor of a jousting system.

**Comment by forcecore** [comment]
Mailaender's attempt seems to unhardcode 1-shot kill.
https://github.com/OpenRA/OpenRA/pull/11715

**Comment by GraionDilach** [comment]
Note that it removes the Angle property from AttackLeap, replacing it with a casual move-imitation, which is why I called that jousting system.

**Comment by forcecore** [comment]
PR made, closing this one
