### ISSUE TITLE
Angry mob

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#194]
For ants, it will be ant swarm.

**Comment by forcecore** [comment]
Visceroid might work for this!

**Comment by MustaphaTR** [comment]
I would be happy to see that too, need for Generals mod.

**Comment by forcecore** [comment]
Soviets: angry mob
Allies: GI

**Comment by forcecore** [comment]
Prototype pushed, need more polishing

**Comment by forcecore** [comment]
Closing. #251 for more work
