### ISSUE TITLE
Production with ranks

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#215]
Bug or intended: When you put a spy on enemys production structures, for example war factory, the new units dont get veterancy bonus on production.
Tested with allies put a spy on war factory and mrls, dismantler etc didnt get veteran bonus when produced.

**Comment by GraionDilach** [comment]
Your new units are missing the ProducibleWithlevel trait the originals define on a per-unit basis.

**Comment by forcecore** [comment]
Fixed in 7d9f2f5256b70b55f3793daaea98bff226d6c6c4
