### ISSUE TITLE
MindController->GiveCondition should be shifted to Mindcontrollable.

### ISSUE THREAD

**Issue by GraionDilach** [forcecore/yupgi_alert0#217]
I'll probably look into this, but this as-is messes up the linter, due to the [GrantedConditionReference] telling the linter to expect that condition being consumed by the actor with the Mindcontroller trait and complaining about missing condition granters on the Mindcontrollable side.

**Comment by forcecore** [comment]
Moved to Mindcontrallable.cs in https://github.com/forcecore/OpenRA/commit/b958263ad5db8c60b6ecbbb648f296feaa62911a
