### ISSUE TITLE
Consider switching PeriodicFreeActor with AS's PeriodicProducer.

### ISSUE THREAD

**Issue by GraionDilach** [forcecore/yupgi_alert0#233]
I'm not sure what the usecase is within the mod, but the AS solution allows to recreate the ZH Reinforcement Pads in an 1:1 method via using ProductionParadrop on the spawner building.

Note that ProduceActorPower - the D2k saboteur SW - also follows the same mindset.

**Comment by forcecore** [comment]
OK

**Comment by forcecore** [comment]
https://github.com/forcecore/OpenRA/commit/d541968c7c66f4f8c3bb7ab64c32f2140d4f80c0
Thank you
