### ISSUE TITLE
Units killed by radiation gives world owner (Neutral) bounty

### ISSUE THREAD

**Issue by MustaphaTR** [forcecore/yupgi_alert0#242]
![bounty](https://user-images.githubusercontent.com/7933210/28908454-717348c2-782c-11e7-8161-714d37d54da9.png)

**Comment by forcecore** [comment]
I'm not sure what the behavior of RA2/Generals is.
Was it that nobody gets XP or bounty?

**Comment by MustaphaTR** [comment]
I just tested with my old YR mod for bountry (vanilla RA2 doesn't have bounty but Ares.dll adds it) with desolator, it doesn't give any bounty if target is killed from radiation at ground. Same should be true for XP too, i always hated in Sov8 you can't just get enemy paradropers at the start fall in radiation and get Desolators rank up, even tho they do when they kill the paradropers normally.

Not sure about generals tho, can't test it right now.

**Comment by GraionDilach** [comment]
Radiation/poison blobs are also ownerless in Generals.

**Comment by forcecore** [comment]
Fixed by https://github.com/forcecore/OpenRA/commit/5b673de476ef58892296c9e3145a48e9900d06d0
