### ISSUE TITLE
Magnetroll Victim Shadow

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#272]
Airplane shadow render code should be useful here

**Comment by GraionDilach** [comment]
https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/Render/WithIdleOverlayOnGround.cs

**Comment by forcecore** [comment]
https://github.com/forcecore/OpenRA/commit/f38014701f439c5e4f6f949011214195c4942938
Ended up copy pasting WithShadow trait
