### ISSUE TITLE
Accept resources trait for a player

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#31]
Needed for a proper MARV.
Current implementation of mods.common has potential bugs...
Whenever any harv virtually dockes in a PROC then it "evicts" from dockedHarv pointer.
When enemy engineer comes and captures the building then the virtual docked one will get captured.
Not good.

**Comment by GraionDilach** [comment]
There's also https://github.com/abcdefg30/OpenRA.Mods.AS/commit/81a86e2c8a2b5088e0f15165b622ce52f1a4126f which never was PRed but I think I'll take it over to get it sorta finished.

**Comment by forcecore** [comment]
Oooh looks good :)

**Comment by GraionDilach** [comment]
Yeah, I remember my main pick with it back then was that it lacks the deploy functionality to start processing anytime, but it's been a while.

**Comment by forcecore** [comment]
Keeping track of "virtually docked" harvesters instead.
Conceptually, chrono harvs need at least 1 alive refinery in my mod.

https://github.com/forcecore/OpenRA/commit/ef13febfc84c4b1591fab62fbef48d0fa90e2223
