### ISSUE TITLE
Labor camp $$$ indication not so visible

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#50]
First of all, the letter is tiny (Problem with default OpenRA)
Second, in C&C generals, they showed $$$ multiple times, not summed up value.
More infantry == the more often you get $$$ gives more visible cue and probably a better way to go.

**Comment by GraionDilach** [comment]
In Generals, the multiple floating values was because different subobjects provided the money.

**Comment by forcecore** [comment]
They could have combined it into one though :) they are contained in one building.

Resolved by commit abd4fe260eb4831411c5ef807df5268478dc8615, money is deposited at once but the floating text is drawn X times.
