### ISSUE TITLE
Ants can be repaired with Service Depot

### ISSUE THREAD

**Issue by MustaphaTR** [forcecore/yupgi_alert0#51]
Doesn't make much sense. If you have an Allied or Soviet Ally you can use theirs to repair your ants.

**Comment by forcecore** [comment]
Thanks for the report. Speaking of repairing, I better check medic (sort of makes sense) and mechanics too.

**Comment by forcecore** [comment]
Fixed in 6f6dcc50e121f760b21f3df934c0897b73bb4edf
