### ISSUE TITLE
Ants faction uses British Flag

### ISSUE THREAD

**Issue by MustaphaTR** [forcecore/yupgi_alert0#53]
I know it must be a placeholder for now but still wanted to say.

I can try to make something if you want.

**Comment by forcecore** [comment]
It would be great if you make something for me :) Currently I have no idea but to use something from Scrin.

**Comment by MustaphaTR** [comment]
I made this using ingame artwork of the ant. I think this is better than using the British Flag.
![creeps](https://cloud.githubusercontent.com/assets/7933210/23576767/3c4dda8c-00b7-11e7-9cb6-ba4d8f87bed8.png)

**Comment by forcecore** [comment]
Thank you, great pixel work!
