### ISSUE TITLE
Grinder (Tier 2 tech). Ants don't self heal nor can be "fixed" but they can be grinded.

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#60]
:D

**Comment by MustaphaTR** [comment]
This shouldn't be hard, i think AcceptsSupplies and SupplyTruck may be way to go. But you may need to edit those and add a type support for those tags, i think they don't have one yet or remobe the normal supply truck.

**Comment by forcecore** [comment]
Indeed, looks very similar to grinder! Thanks

**Comment by GraionDilach** [comment]
The SupplyTruck generalization PR hit bleed, so I guess this should wait til next release cycle?

**Comment by forcecore** [comment]
I think so too

**Comment by forcecore** [comment]
Cherry picked commits by @reaperrr then
74d6d9c46555e145601e1a7d72ca4281f8961d8f : INotifyCashTransfer
a855c2300d0a0e7f3556cd37040749b8b5ad2ad4 : Cash transfer sounds (using INotifyCashTransfer, both the victim and grinder side. (I'm using victim side only in my mod though)
0d17f7a6379297b88e3803a13bb2be54be9c1b28 : Grinding animation trait (INotifyCashTransfer again)

**Comment by forcecore** [comment]
Hmmm I think these changes look good for upstream too but not sure if they'd need them.
