### ISSUE TITLE
Desolator Cameo uses RA2 Font

### ISSUE THREAD

**Issue by MustaphaTR** [forcecore/yupgi_alert0#70]
SHP builder uses RA2 font even when you select RA1 Camo style, so you may need to do it manually.

Differences for example are RA1 has a longer E and doesn't have a gradient, it is comletely white.

**Comment by forcecore** [comment]
I'm postponing the fix for this, I think OpenRA has a plan to remove all letters from the cameos and make the game engine write letters according to the string table for the modders, similarly to Tiberian Sun way.

**Comment by GraionDilach** [comment]
I don't believe there is such a plan.

**Comment by forcecore** [comment]
You're right.
https://github.com/OpenRA/OpenRA/issues/2824

Urgh I dug up the issue again and it is closed :(

**Comment by MustaphaTR** [comment]
You acn find testless icons on CnC Wikia page, if you wanna use them on your mod.

**Comment by forcecore** [comment]
* Replacing ticket with #195
