### ISSUE TITLE
YAML checking for Playtest-20170304

### ISSUE THREAD

**Issue by forcecore** [forcecore/yupgi_alert0#78]
Well, EVERYTHING is affected, more or less.

- [x] Tooltips
- [x] NMIG (airborne condition), MIG2, ZEP
- [x] Falling husks
- [x] AttackSequence --> DefaultAttackSequence (with infantry body)
- [x] PrimaryBuilding

**Comment by MustaphaTR** [comment]
I think you can just update everthing related to yaml just using unility's upgrade commands. Dll would need some work tho.

**Comment by forcecore** [comment]
Unfortunately, the utility seems to give me only errors :(

**Comment by forcecore** [comment]
All fixed, around 1ad43044f254236e834dfdd790bc51d869912106
There might be some left-overs but things work without crash.
